name: Déploiement sur VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Déployer sur le VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/html/projet-final
            git pull origin main
            docker compose down
            docker compose up -d --build
            ./vendor/bin/sail artisan migrate --force
            ./vendor/bin/sail artisan cache:clear
            ./vendor/bin/sail artisan config:clear
            ./vendor/bin/sail artisan route:clear